import 'package:hive/hive.dart';

part 'task.g.dart';
// This file is generated by Hive and contains the adapter for the Task class. It should not be modified manually.
//an adapter class is used to convert the Task object to a format that can be stored in Hive and vice versa.
//The typeId is a unique identifier for the Task class, and the fields are annotated with @HiveField to specify
//their order in the binary representation. The Task class itself extends HiveObject,
//which provides methods for saving, deleting, and updating the object in the Hive database.

@HiveType(typeId: 0)
// The typeId is a unique identifier for the Task class.
//It should be a positive integer and should not conflict with other typeIds used in the application.
class Task extends HiveObject {
  @HiveField(
    0,
  ) // The HiveField annotation is used to specify the order of the fields in the binary representation.
  String title;

  @HiveField(1)
  String description;

  @HiveField(2)
  DateTime dueDate;

  @HiveField(3)
  String priority;

  @HiveField(4)
  bool isCompleted;

  @HiveField(5)
  String category;

  @HiveField(6)
  bool isDeleted;
  // New field to mark tasks as deleted without removing them from Hive

  @HiveField(7)
  DateTime? deletedAt;

  @HiveField(8)
  String tid;

  @HiveField(9)
  DateTime? createdAt;

  Task({
    // The constructor for the Task class. It takes the title as a required parameter and the other fields as
    //optional parameters with default values.
    required this.title,
    required this.description,
    required this.dueDate,
    required this.priority,
    this.isCompleted = false,
    /////////
    required this.category,
    this.isDeleted = false,
    this.deletedAt,
    this.tid = "",
    this.createdAt,
  });
}
